# Generated by Django 5.1.2 on 2024-11-27 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tiempo_estimado', models.DurationField()),
                ('imagen', models.ImageField(upload_to='servicios/')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('total_ganado', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total_adelantos', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('servicios', models.ManyToManyField(blank=True, to='spa.servicio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('pago', models.CharField(default='efectivo', max_length=20)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('precio_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa.servicio')),
                ('trabajador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spa.trabajador')),
            ],
        ),
    ]
